<?php

return [
    'hidden_works' => [
        'label' => 'Акт освидетельствования скрытых работ',
        'group' => '1.4 Земляные работы',
        'model' => \App\Models\HiddenWork::class,
        'pdf' => 'hiddens_work.pdf',
        'validation' => [
            'type' => 'required|string',
            'act_number' => 'required|string',
            'act_date' => 'required|date',
            'object_name' => 'required|string',
            'passport_id' => 'required|exists:passports,id',
            'heading_key' => 'required|string',
            'heading_text' => 'required|string|max:255',

            // Комиссия
            'contractor_representative' => 'required|string',
            'tech_supervisor_representative' => 'required|string',
            'author_supervisor_representative' => 'nullable|string',
            'additional_participants' => 'nullable|string',

            // Работы
            'work_executor' => 'required|string',
            'hidden_works' => 'required|string',
            'psd_info' => 'required|string',
            'materials' => 'nullable|string',
            'compliance_evidence' => 'nullable|string',
            'deviations' => 'nullable|string',
            'start_date' => 'nullable|date',
            'end_date' => 'nullable|date',
            'commission_decision' => 'required|string',
            'next_works' => 'nullable|string',

            // Подписи
            'contractor_sign_name' => 'required|string',
            'tech_supervisor_sign_name' => 'required|string',
            'author_supervisor_sign_name' => 'nullable|string',
        ],
        'fields' => [
            'act_number',
            'city',
            'act_date',
            'object_name',
            'contractor_representative',
            'tech_supervisor_representative',
            'author_supervisor_representative',
            'additional_participants',
            'work_executor',
            'hidden_works',
            'psd_info',
            'materials',
            'compliance_evidence',
            'deviations',
            'start_date',
            'end_date',
            'commission_decision',
            'next_works',
            'contractor_sign_name',
            'tech_supervisor_sign_name',
            'author_supervisor_sign_name',
            'heading_text',
            'heading_key',
        ],
    ],
    'intermediate_accept' => [
        'label' => 'Промежуточное освидетельствование',
        'group' => 'Общая документация для всех видов производимых работ',
        'model' => \App\Models\IntermediateAccept::class,
        'pdf' => 'intermediate_accept.pdf',
        'view' => 'acts.templates.intermediate_accept',
        'validation' => [
            'type' => 'required|string',
            'passport_id' => 'required|exists:passports,id',
            'act_number' => 'required|string',
            'act_date' => 'required|date',
            'object_name' => 'required|string',
            'contractor_representative' => 'required|string',
            'tech_supervisor_representative' => 'required|string',
            'author_supervisor_representative' => 'nullable|string',
            'additional_participants' => 'nullable|string',
            'construction_stage' => 'nullable|string',
            'accepted_elements' => 'nullable|string',
            'hidden_works_status' => 'nullable|string',
            'compliance_info' => 'nullable|string',
            'psd_info' => 'nullable|string',
            'geodetic_info' => 'nullable|string',
            'test_results' => 'nullable|string',
            'commission_decision' => 'required|string',
            'next_works' => 'nullable|string',
            'contractor_sign_name' => 'required|string',
            'tech_supervisor_sign_name' => 'required|string',
            'author_supervisor_sign_name' => 'nullable|string',
        ],
        'fields' => [
            'act_number',
            'act_date',
            'object_name',
            'contractor_representative',
            'tech_supervisor_representative',
            'author_supervisor_representative',
            'additional_participants',
            'construction_stage',
            'accepted_elements',
            'hidden_works_status',
            'compliance_info',
            'psd_info',
            'geodetic_info',
            'test_results',
            'commission_decision',
            'next_works',
            'contractor_sign_name',
            'tech_supervisor_sign_name',
            'author_supervisor_sign_name',
        ],
    ],
    'prilozeniye_21' => [
        'label' => 'Акт приемки геодезической разбивочной основы для строительства',
        'group' => '1.3 Геодезические работы (ГОТОВ)',
        'model' => \App\Models\Prilozeniye_21::class,
        'pdf' => '21.pdf',
        'view' => 'acts.templates.prilozeniye_21',
        'validation' => [
            'passport_id' => 'required|exists:passports,id',
            'number_acts' => 'required|string',
            'name_object' => 'required|string',
            'city' => 'required|string',
            'day' => 'required|integer',
            'month' => 'required|string',
            'year' => 'required|integer',

            'pred_zakaz' => 'required|string',
            'pred_tn' => 'required|string',
            'pred_gp' => 'required|string',

            'geodez_docs' => 'required|string',
            'tech_docs_1' => 'required|string',
            'tech_docs_2' => 'nullable|string',
            'prilojenie_1' => 'nullable|string',
            'prilojenie_2' => 'nullable|string',
        ],
        'fields' => [
            'number_acts',
            'name_object',
            'city',
            'day',
            'month',
            'year',
            'pred_zakaz',
            'pred_tn',
            'pred_gp',
            'geodez_docs',
            'tech_docs_1',
            'tech_docs_2',
            'prilojenie_1',
            'prilojenie_2',
        ],
    ],
    'prilozeniye_22' => [
        'label' => 'Акт приемки-передачи результатов геодезических работ при строительстве зданий (сооружений)',
        'group' => '1.3 Геодезические работы (ГОТОВ)',
        'model' => \App\Models\Prilozeniye_22::class,
        'pdf' => '22.pdf',
        'view' => 'acts.templates.prilozeniye_22', // имя blade-файла = resources/views/acts/templates/prilozeniye_22.blade.php
        'validation' => [
            'passport_id' => 'required|exists:passports,id',
            'number_acts' => 'required|string',
            'month' => 'required|string',
            'city' => 'required|string',
            'name_object' => 'required|string',
            'pred_sm_pered_fio' => 'required|string',
            'pred_sm_prinim_fio' => 'required|string',
            'name_object_1' => 'nullable|string',
            'pred_sm_pered_comp' => 'required|string',
            'pred_sm_prinim_comp' => 'required|string',
            'name_object_2' => 'nullable|string',
            'prilojeniya' => 'nullable|string',
            'pred_sm_pered' => 'required|string',
            'pred_sm_prinim' => 'required|string',
            'day' => 'required|integer',
            'year' => 'required|integer',
        ],
        'fields' => [
            'number_acts',
            'month',
            'city',
            'name_object',
            'pred_sm_pered_fio',
            'pred_sm_prinim_fio',
            'name_object_1',
            'pred_sm_pered_comp',
            'pred_sm_prinim_comp',
            'name_object_2',
            'prilojeniya',
            'pred_sm_pered',
            'pred_sm_prinim',
            'day',
            'year',
        ],
    ],
    'prilozeniye_23' => [
        'label' => 'Акт посадки здания',
        'group' => '1.3 Геодезические работы (ГОТОВ)',
        'model' => \App\Models\Prilozeniye_23::class,
        'pdf' => '23.pdf',
        'view' => 'acts.templates.prilozeniye_23',
        'validation' => [
            'passport_id' => 'required|exists:passports,id',
            'number_acts' => 'required|string',
            'name_object' => 'required|string',
            'city' => 'required|string',
            'day' => 'required|integer',
            'month' => 'required|string',
            'year' => 'required|integer',
            'pred_zakaz' => 'required|string',
            'pred_tn' => 'required|string',
            'pred_gp' => 'required|string',
            'geodez_docs' => 'nullable|string',
            'tech_docs_1' => 'nullable|string',
            'tech_docs_2' => 'nullable|string',
            'prilojenie_1' => 'nullable|string',
            'prilojenie_2' => 'nullable|string',
        ],
        'fields' => [
            'number_acts',
            'name_object',
            'city',
            'day',
            'month',
            'year',
            'pred_zakaz',
            'pred_tn',
            'pred_gp',
            'geodez_docs',
            'tech_docs_1',
            'tech_docs_2',
            'prilojenie_1',
            'prilojenie_2',
        ],
    ],
    'prilozeniye_24' => [
        'label' => 'Акт переноса отметки на репер',
        'group' => '1.3 Геодезические работы (ГОТОВ)',
        'model' => \App\Models\Prilozeniye_24::class,
        'pdf' => '24.pdf',
        'view' => 'acts.templates.prilozeniye_24',
        'validation' => [
            'city' => 'required|string',
            'day' => 'required|integer',
            'number_act' => 'required|string',
            'month' => 'required|string',
            'year' => 'required|integer',
            'pred_zk' => 'required|string',
            'pred_gp' => 'required|string',
            'pred_upr' => 'required|string',
            'name_object_address' => 'required|string',
            'otmetka_reper' => 'required|string',
            'null_otmetka' => 'required|string',
            'name_zdamiya' => 'required|string',
            'passport_id' => 'required|exists:passports,id',
        ],
        'fields' => [
            'city',
            'day',
            'number_act',
            'month',
            'year',
            'pred_zk',
            'pred_gp',
            'pred_upr',
            'name_object_address',
            'otmetka_reper',
            'null_otmetka',
            'name_zdamiya',
        ],
    ],
    'prilozeniye_26' => [
        'label' => 'Акт геодезической проверки положения конструктивного элемента мостового сооружения в плане и профиле',
        'group' => '1.3 Геодезические работы (ГОТОВ)',
        'model' => \App\Models\Prilozeniye_26::class,
        'pdf' => '26.pdf',
        'view' => 'acts.templates.prilozeniye_26',
        'validation' => [
            'number_acts'    => 'required|string',
            'day'            => 'required|integer',
            'month'          => 'required|string',
            'year'           => 'required|integer',
            'glav_injener'   => 'required|string',
            'komisiay'       => 'required|string',
            'geodez_prov'    => 'required|string',
            'number_rep'     => 'required|string',
            'otmetka_rep'    => 'required|string',
            'zakl'           => 'required|string',
            'snip'           => 'required|string',
            'passport_id'    => 'required|exists:passports,id',
        ],
        'fields' => [
            'number_acts',
            'day',
            'month',
            'year',
            'glav_injener',
            'komisiay',
            'geodez_prov',
            'number_rep',
            'otmetka_rep',
            'zakl',
            'snip',
        ],
    ],
    'prilozeniye_27' => [
        'group' => 'Общая документация для всех видов производимых работ',
        'label' => 'Акт освидетельствования и приемки котлована',
        'model' => \App\Models\Prilozeniye_27::class,
        'pdf' => '27.pdf',
        'view' => 'acts.templates.prilozeniye_27',
        'validation' => [
            'stroi_org' => 'required|string',
            'name_address' => 'required|string',
            'number_acts' => 'required|string',
            'kotlovan_pod' => 'nullable|string',
            'day' => 'required|integer',
            'month' => 'required|string',
            'year' => 'required|integer',
            'komisia_fio' => 'required|string',
            'komisia_osn' => 'nullable|string',
            'komisia_osn_2' => 'nullable|string',
            'komisia_osn_3' => 'nullable|string',
            'pod' => 'nullable|string',
            'number_krep' => 'nullable|string',
            'razrab' => 'nullable|string',
            'jurnal_rb_number' => 'nullable|string',
            'jurnal_number' => 'nullable|string',
            'akt_number' => 'nullable|string',
            'vedomost' => 'nullable|string',
            'estestv_poverh' => 'nullable|string',
            'kotlovan_otm' => 'nullable|string',
            'project_otm' => 'nullable|string',
            'reper_number' => 'nullable|string',
            'reper_otm' => 'nullable|string',
            'vyp_iz' => 'nullable|string',
            'ot_dna' => 'nullable|string',
            'do_m' => 'nullable|string',
            'glubina_zabivki' => 'nullable|string',
            'verh_org' => 'nullable|string',
            'otkloneniya_shpunt' => 'nullable|string',
            'krep_verh' => 'nullable|string',
            'obvyazka' => 'nullable|string',
            'zamknutost_shpunt' => 'nullable|string',
            'number_prilojeniya' => 'nullable|string',
            'otmetka_vod' => 'nullable|string',
            'otmetka_rab_gorizont_vod' => 'nullable|string',
            'vodootliv' => 'nullable|string',
            'grunt_dno' => 'nullable|string',
            'glubina_shunt' => 'nullable|string',
            'idet' => 'nullable|string',
            'zaglush_key' => 'nullable|string',
            'ispytaniya_grunt' => 'nullable|string',
            'rachet_sopr' => 'nullable|string',
            'sopr_project' => 'nullable|string',
            'otmetka_razr' => 'nullable|string',
            'day_shunt' => 'nullable|integer',
            'month_shunt' => 'nullable|string',
            'year_shunt' => 'nullable|integer',
            'passport_id' => 'required|exists:passports,id',
        ],
        'fields' => [
            'stroi_org',
            'name_address',
            'number_acts',
            'kotlovan_pod',
            'day',
            'month',
            'year',
            'komisia_fio',
            'komisia_osn',
            'komisia_osn_2',
            'komisia_osn_3',
            'pod',
            'number_krep',
            'razrab',
            'jurnal_rb_number',
            'jurnal_number',
            'akt_number',
            'vedomost',
            'estestv_poverh',
            'kotlovan_otm',
            'project_otm',
            'reper_number',
            'reper_otm',
            'vyp_iz',
            'ot_dna',
            'do_m',
            'glubina_zabivki',
            'verh_org',
            'otkloneniya_shpunt',
            'krep_verh',
            'obvyazka',
            'zamknutost_shpunt',
            'number_prilojeniya',
            'otmetka_vod',
            'otmetka_rab_gorizont_vod',
            'vodootliv',
            'grunt_dno',
            'glubina_shunt',
            'idet',
            'zaglush_key',
            'ispytaniya_grunt',
            'rachet_sopr',
            'sopr_project',
            'otmetka_razr',
            'day_shunt',
            'month_shunt',
            'year_shunt',
        ],
    ],
    'prilozeniye_28' => [
        'label' => 'Акт освидетельствования и приемки свайного фундамента на забивных сваях (шпунтового ряда)',
        'group' => '1.4 Земляные работы',
        'model' => \App\Models\Prilozeniye_28::class,
        'pdf' => '28.pdf',
        'view' => 'acts.templates.prilozeniye_28',
        'validation' => [
            'number_acts_1'    => 'required|string',
            'stroi_org'        => 'required|string',
            'name_address'     => 'required|string',
            'day'              => 'required|integer',
            'month'            => 'required|string',
            'year'             => 'required|integer',
            'komisiya'         => 'required|string',
            'svain_osn_1'      => 'nullable|string',
            'svain_osn_2'      => 'nullable|string',
            'svain_osn_3'      => 'nullable|string',
            'krepleniye_numb'  => 'nullable|string',
            'name_org'         => 'nullable|string',
            'jurn_pr'          => 'nullable|string',
            'jurn_an'          => 'nullable|string',
            'jurn_tn'          => 'nullable|string',
            'otmetka_grunta'   => 'nullable|string',
            'srezka_otmetka'   => 'nullable|string',
            'vyryt_otmetka'    => 'nullable|string',
            'project_otmetka'  => 'nullable|string',
            'passport-svai'    => 'nullable|string',
            'reper'            => 'nullable|string',
            'otmetka-reper'    => 'nullable|string',
            'krepleniye'       => 'nullable|string',
            'krep-material'    => 'nullable|string',
            'glubina_ot'       => 'nullable|string',
            'glubina_do'       => 'nullable|string',
            'glubina_project'  => 'nullable|string',
            'glubina_org'      => 'nullable|string',
            'sootvetstv'       => 'nullable|string',
            'voda_niz'         => 'nullable|string',
            'vodootliv'        => 'nullable|string',
            'vne_kotl'         => 'nullable|string',
            'intens_voda'      => 'nullable|string',
            'grynt_glubina'    => 'nullable|string',
            'jurnal'           => 'nullable|string',
            'kolvo'            => 'nullable|string',
            'number_acts'      => 'nullable|string',
            'day-act'          => 'nullable|integer',
            'month-act'        => 'nullable|string',
            'year-act'         => 'nullable|integer',
            'postanovila'      => 'nullable|string',
            'kachstv'          => 'nullable|string',
            'daln_rab'         => 'nullable|string',
            'passport_id'      => 'required|exists:passports,id',
        ],
        'fields' => [
            'number_acts_1',
            'stroi_org',
            'name_address',
            'day',
            'month',
            'year',
            'komisiya',
            'svain_osn_1',
            'svain_osn_2',
            'svain_osn_3',
            'krepleniye_numb',
            'name_org',
            'jurn_pr',
            'jurn_an',
            'jurn_tn',
            'otmetka_grunta',
            'srezka_otmetka',
            'vyryt_otmetka',
            'project_otmetka',
            'passport-svai',
            'reper',
            'otmetka-reper',
            'krepleniye',
            'krep-material',
            'glubina_ot',
            'glubina_do',
            'glubina_project',
            'glubina_org',
            'sootvetstv',
            'voda_niz',
            'vodootliv',
            'vne_kotl',
            'intens_voda',
            'grynt_glubina',
            'jurnal',
            'kolvo',
            'number_acts',
            'day-act',
            'month-act',
            'year-act',
            'postanovila',
            'kachstv',
            'daln_rab',
        ],
    ],
    'prilozeniye_29' => [
        'label' => 'Акт освидетельствования и приемки полости пробуренной скважины для бетонирования столба, скважин в основании оболочки, уширения',
        'group' => '1.4 Земляные работы',
        'model' => \App\Models\Prilozeniye_29::class,
        'pdf' => '29.pdf',
        'view' => 'acts.templates.prilozeniye_29',
        'validation' => [
            'stroi_org'                => 'required|string',
            'name_address'             => 'required|string',
            'number_acts'              => 'required|string',
            'number_fund'              => 'nullable|string',
            'number_opora'             => 'nullable|string',
            'day'                      => 'required|integer',
            'month'                    => 'required|string',
            'year'                     => 'required|integer',
            'komisiya'                 => 'required|string',
            'name_stroi'               => 'nullable|string',
            'stroi_fio'                => 'nullable|string',
            'tn_fio'                   => 'nullable|string',
            'ushireniya_numb'          => 'nullable|string',
            'opora_numb'               => 'nullable|string',
            'chertej'                  => 'nullable|string',
            'diametr'                  => 'nullable|string',
            'tolshina'                 => 'nullable|string',
            'dlina'                    => 'nullable|string',
            'otmetka'                  => 'nullable|string',
            'skv_diametr'              => 'nullable|string',
            'skv_verh'                 => 'nullable|string',
            'skv_dno'                  => 'nullable|string',
            'stanok_neskal'            => 'nullable|string',
            'neskal_glubina'           => 'nullable|string',
            'stanok_skal'              => 'nullable|string',
            'skal_glubina'             => 'nullable|string',
            'diametr_razbur'           => 'nullable|string',
            'otmetk_podoshv'           => 'nullable|string',
            'silindr_visota'           => 'nullable|string',
            'uroven_vod'               => 'nullable|string',
            'voda_vne'                 => 'nullable|string',
            'grunt_osnov'              => 'nullable|string',
            'otkloneniya_vdol'         => 'nullable|string',
            'otkloneniya_poperek'      => 'nullable|string',
            'otkloneniya_vertical'     => 'nullable|string',
            'dlina_karkas'             => 'nullable|string',
            'diametr_karkas'           => 'nullable|string',
            'niz_karkas'               => 'nullable|string',
            'armkarkas_s'              => 'nullable|string',
            'sterjen_diam'             => 'nullable|string',
            'sterjen_mm'               => 'nullable|string',
            'project'                  => 'nullable|string',
            'number_project'           => 'nullable|string',
            'ustanovleno'              => 'nullable|string',
            'postanovili'              => 'nullable|string',
            'kachestvo'                => 'nullable|string',
            'passport_id'              => 'required|exists:passports,id',
        ],
        'fields' => [
            'stroi_org',
            'name_address',
            'number_acts',
            'number_fund',
            'number_opora',
            'day',
            'month',
            'year',
            'komisiya',
            'name_stroi',
            'stroi_fio',
            'tn_fio',
            'ushireniya_numb',
            'opora_numb',
            'chertej',
            'diametr',
            'tolshina',
            'dlina',
            'otmetka',
            'skv_diametr',
            'skv_verh',
            'skv_dno',
            'stanok_neskal',
            'neskal_glubina',
            'stanok_skal',
            'skal_glubina',
            'diametr_razbur',
            'otmetk_podoshv',
            'silindr_visota',
            'uroven_vod',
            'voda_vne',
            'grunt_osnov',
            'otkloneniya_vdol',
            'otkloneniya_poperek',
            'otkloneniya_vertical',
            'dlina_karkas',
            'diametr_karkas',
            'niz_karkas',
            'armkarkas_s',
            'sterjen_diam',
            'sterjen_mm',
            'project',
            'number_project',
            'ustanovleno',
            'postanovili',
            'kachestvo',
        ],
    ],
    'prilozeniye_30' => [
        'label' => 'Акт осмотра открытых рвов и котлованов под фундаменты',
        'group' => '1.4 Земляные работы',
        'model' => \App\Models\Prilozeniye_30::class,
        'pdf' => '30.pdf',
        'view' => 'acts.templates.prilozeniye_30',
        'validation' => [
            'act_number'        => 'required|string',
            'city'              => 'required|string',
            'day'               => 'required|integer',
            'month'             => 'required|string',
            'year'              => 'required|integer',
            'pred_tn_zastroi'   => 'nullable|string',
            'injener_1'         => 'nullable|string',
            'injener_2'         => 'nullable|string',
            'glav_injener_1'    => 'nullable|string',
            'glav_injener_2'    => 'nullable|string',
            'proizod_rabot'     => 'nullable|string',
            'number_zeml_uch'   => 'nullable|string',
            'address'           => 'nullable|string',
            'grunt_vod'         => 'nullable|string',
            'plan_otm'          => 'nullable|string',
            'glubina'           => 'nullable|string',
            'glubina_v_prep'    => 'nullable|string',
            'prepyatstv'        => 'nullable|string',
            'perv_osnov'        => 'nullable|string',
            'davl_grunt'        => 'nullable|string',
            'davl_grunt_2'      => 'nullable|string',
            'davl_project'      => 'nullable|string',
            'ukrep_vyzyv'       => 'nullable|string',
            'osad_sh'           => 'nullable|string',
            'kom_davlemiy'      => 'nullable|string',
            'avtor'             => 'nullable|string',
            'tn_zastr'          => 'nullable|string',
            'inj_1'             => 'nullable|string',
            'inj_2'             => 'nullable|string',
            'glav_injener'      => 'nullable|string',
            'proizvod_rabot'    => 'nullable|string',
            'passport_id'       => 'required|exists:passports,id',
        ],
        'fields' => [
            'act_number',
            'city',
            'day',
            'month',
            'year',
            'pred_tn_zastroi',
            'injener_1',
            'injener_2',
            'glav_injener_1',
            'glav_injener_2',
            'proizod_rabot',
            'number_zeml_uch',
            'address',
            'grunt_vod',
            'plan_otm',
            'glubina',
            'glubina_v_prep',
            'prepyatstv',
            'perv_osnov',
            'davl_grunt',
            'davl_grunt_2',
            'davl_project',
            'ukrep_vyzyv',
            'osad_sh',
            'kom_davlemiy',
            'avtor',
            'tn_zastr',
            'inj_1',
            'inj_2',
            'glav_injener',
            'proizvod_rabot',
        ],
    ],
    'prilozeniye_31' => [
        'label' => 'Акт об изготовлении контрольных образцов бетона',
        'group' => 'Общая документация для всех видов производимых работ',
        'model' => \App\Models\Prilozeniye_31::class,
        'pdf' => '31.pdf',
        'view'  => 'acts.templates.prilozeniye_31',
        'validation' => [
            'day'            => 'required|integer',
            'month'          => 'required|string',
            'year'           => 'required|integer',
            'number_acts'    => 'required|string',
            'day_izgot'      => 'nullable|integer',
            'month_izgot'    => 'nullable|string',
            'seria'          => 'nullable|string',
            'number_obr'     => 'nullable|string',
            'markirovka'     => 'nullable|string',
            'kolvo'          => 'nullable|integer',
            'razmer'         => 'nullable|string',
            'name_constr'    => 'nullable|string',
            'number_card'    => 'nullable|string',
            'class_beton'    => 'nullable|string',
            'vodosement'     => 'nullable|string',
            'osadka'         => 'nullable|string',
            'sek'            => 'nullable|string',
            'temp'           => 'nullable|string',
            'betonomesh'     => 'nullable|string',
            'forms'          => 'nullable|string',
            'srok_raspalubki'=> 'nullable|string',
            'uslovia'        => 'nullable|string',
            'zapic_jurnal'   => 'nullable|string',
            'passport_id'    => 'required|exists:passports,id',
        ],
        'fields' => [
            'day',
            'month',
            'year',
            'number_acts',
            'day_izgot',
            'month_izgot',
            'seria',
            'number_obr',
            'markirovka',
            'kolvo',
            'razmer',
            'name_constr',
            'number_card',
            'class_beton',
            'vodosement',
            'osadka',
            'sek',
            'temp',
            'betonomesh',
            'forms',
            'srok_raspalubki',
            'uslovia',
            'zapic_jurnal',
        ],
    ],
    'prilozeniye_32' => [
        'group' => 'Общая документация для всех видов производимых работ',
        'label' => 'Акт приемки ответственных специальных вспомогательных сооружений (приспособлений, устройств) для строительства мостового сооружения',
        'model' => \App\Models\Prilozeniye_32::class,
        'pdf' => '32.pdf',
        'view' => 'acts.templates.prilozeniye_32',
        'validation' => [
            'stroi_org'                    => 'required|string',
            'name_address'                 => 'required|string',
            'number_acts'                  => 'required|string',
            'day#0'                        => 'required|integer',
            'month'                        => 'required|string',
            'year'                         => 'required|integer',
            'komisia'                      => 'required|string',
            'osnovaniye'                   => 'required|string',
            'name_adress_naznacheniye_2'   => 'required|string',
            'rabochie'                     => 'nullable|string',
            'razrabotanye'                 => 'nullable|string',
            'otklonenie_1'                 => 'nullable|string',
            'otklonenie_2'                 => 'nullable|string',
            'day#1'                        => 'nullable|integer',
            'year_sogl'                    => 'nullable|integer',
            'name_adress_naznacheniye_1'   => 'nullable|string',
            'jurnal_proizv'                => 'nullable|string',
            'jurnan_avtor'                 => 'nullable|string',
            'akts'                         => 'nullable|string',
            'sertifikat'                   => 'nullable|string',
            'passport'                     => 'nullable|string',
            'ustanovila_1'                 => 'nullable|string',
            'ustanovila_2'                 => 'nullable|string',
            'chitat_rabots'                => 'nullable|string',
            'priznat'                      => 'nullable|string',
            'razreshit'                    => 'nullable|string',
            'passport_id'                  => 'required|exists:passports,id',
        ],
        'fields' => [
            'stroi_org',
            'name_address',
            'number_acts',
            'day#0',
            'month',
            'year',
            'komisia',
            'osnovaniye',
            'name_adress_naznacheniye_2',
            'rabochie',
            'razrabotanye',
            'otklonenie_1',
            'otklonenie_2',
            'day#1',
            'year_sogl',
            'name_adress_naznacheniye_1',
            'jurnal_proizv',
            'jurnan_avtor',
            'akts',
            'sertifikat',
            'passport',
            'ustanovila_1',
            'ustanovila_2',
            'chitat_rabots',
            'priznat',
            'razreshit',
        ],
    ],
    'prilozeniye_67' => [
        'label' => 'Акт проверки мусоропровода',
        'group' => 'Общая документация для всех видов производимых работ',
        'model' => \App\Models\Prilozeniye_67::class,
        'pdf' => '67.pdf',
        'view'  => 'acts.templates.prilozeniye_67',
        'number_field' => 'number_acts',
        'validation' => [
            'number_acts'     => 'required|string',   // Номер акта
            'name_rabot'      => 'required|string',   // Наименование работ (например: устройство мусоропровода)
            'name_address'    => 'required|string',   // Место расположения объекта
            'date'            => 'required|date',     // Дата составления акта
            'month'           => 'nullable|string',
            'year'            => 'nullable|integer',
            'cmo_1'           => 'required|string',   // Представитель СМО (ФИО, должность)
            'cmo_2'           => 'nullable|string',
            'tnz_1'           => 'required|string',   // Представитель технадзора (ФИО, должность)
            'tnz_2'           => 'nullable|string',
            'smo_prov_1_0'    => 'nullable|string',
            'smo_prov_1_1'    => 'nullable|string',
            'rabot'           => 'required|string',   // Название СМО, выполнившей работы
            'psd_1'           => 'nullable|string',   // Наименование проектной организации, № чертежей, дата
            'psd_2'           => 'nullable|string',
            'material_1'      => 'nullable|string',   // Наименование материалов
            'material_2'      => 'nullable|string',
            'passport_id'     => 'required|exists:passports,id',
        ],
        'fields' => [
            'number_acts',
            'name_rabot',
            'name_address',
            'date',
            'month',
            'year',
            'cmo_1',
            'cmo_2',
            'tnz_1',
            'tnz_2',
            'smo_prov_1_0',
            'smo_prov_1_1',
            'rabot',
            'psd_1',
            'psd_2',
            'material_1',
            'material_2',
        ],
    ],
    'prilozeniye_72' => [
        'label' => 'Акт приемки систем естественной вентиляции',
        'group' => 'Общая документация для всех видов производимых работ',
        'model' => \App\Models\Prilozeniye_72::class,
        'pdf' => '72.pdf',
        'view'  => 'acts.templates.prilozeniye_72',
        'number_field' => 'number_acts',
        'validation' => [
            'number_acts'    => 'required|string',
            'city'           => 'required|string',
            'month'          => 'required|string',
            'year'           => 'required|integer',
            'tnz'            => 'nullable|string',
            'an'             => 'nullable|string',
            'po'             => 'nullable|string',
            'subpo'          => 'nullable|string',
            'day'            => 'required|integer',
            'name_address'   => 'required|string',
            'passport_id'    => 'required|exists:passports,id',
        ],
        'fields' => [
            'number_acts',
            'city',
            'month',
            'year',
            'tnz',
            'an',
            'po',
            'subpo',
            'day',
            'name_address',
        ],
    ],

    'prilozeniye_73' => [
        'group' => 'Климат и вентиляция',
        'label' => 'Акт приёмки систем кондиционирования воздуха',
        'model' => \App\Models\Prilozeniye_73::class,
        'pdf'   => '73.pdf',
        'view'  => 'acts.templates.prilozeniye_73',
        'number_field' => 'number_act',
        'validation' => [
            'number_act'   => 'required|string',
            'city'         => 'required|string',
            'day'          => 'required|integer',
            'month'        => 'required|string',
            'year'         => 'required|integer',
            'an'           => 'nullable|string',
            'tnz'          => 'nullable|string',
            'po'           => 'nullable|string',
            'subpo'        => 'nullable|string',
            'exploat'      => 'nullable|string',
            'exploat_fio'  => 'nullable|string',
            'object_name'  => 'required|string',
            'address'      => 'required|string',
            'docs_text'    => 'nullable|string',
            'passport_id'  => 'required|exists:passports,id',
        ],
        'fields' => [
            'number_act',
            'city',
            'day',
            'month',
            'year',
            'an',
            'tnz',
            'po',
            'subpo',
            'exploat',
            'exploat_fio',
            'object_name',
            'address',
            'docs_text',
        ],
    ],
    'prilozeniye_74' => [
        'group' => 'Климат и вентиляция',
        'label' => 'Акт приёмки систем пылеудаления',
        'model' => \App\Models\Prilozeniye_74::class,
        'pdf'   => '74.pdf',
        'view'  => 'acts.templates.prilozeniye_74',
        'number_field' => 'number_acts',
        'validation' => [
            'number_acts'   => 'required|string',
            'city'         => 'required|string',
            'day'          => 'required|integer',
            'month'        => 'required|string',
            'year'         => 'required|integer',
            'an'           => 'nullable|string',
            'tnz'          => 'nullable|string',
            'po'           => 'nullable|string',
            'subpo'        => 'nullable|string',
            'exploat'      => 'nullable|string',
            'exploat_fio'  => 'nullable|string',
            'object_name'  => 'required|string',
            'docs'         => 'nullable|string',
            'passport_id'  => 'required|exists:passports,id',
        ],
        'fields' => [
            'number_acts',
            'city',
            'day',
            'month',
            'year',
            'an',
            'tnz',
            'po',
            'subpo',
            'exploat',
            'exploat_fio',
            'object_name',
            'docs',
        ],
    ],
    'prilozeniye_75' => [
        'group' => 'Электрика, молниезащита',
        'label' => 'Акт приёмки молниезащиты',
        'model' => \App\Models\Prilozeniye_75::class,
        'pdf'   => '75.pdf',
        'view'  => 'acts.templates.prilozeniye_75',
        'number_field' => 'number_acts',
        'validation' => [
            'number_acts'   => 'required|string',
            'city'         => 'required|string',
            'day'          => 'required|integer',
            'month'        => 'required|string',
            'year'         => 'required|integer',
            'an'           => 'nullable|string',
            'tnz'          => 'nullable|string',
            'po'           => 'nullable|string',
            'subpo'        => 'nullable|string',
            'exploat'      => 'nullable|string',
            'object_name'  => 'required|string',
            'docs'         => 'nullable|string',
            'passport_id'  => 'required|exists:passports,id',
        ],
        'fields' => [
            'number_acts',
            'city',
            'day',
            'month',
            'year',
            'an',
            'tnz',
            'po',
            'subpo',
            'exploat',
            'object_name',
            'docs',
        ],
    ],
    'prilozeniye_gotovn_podmostei' => [
        'group' => 'Лифтовое оборудование',
        'label' => 'Акт готовности подмостей для монтажа лифтов',
        'model' => \App\Models\PrilozeniyeGotovnPodmostei::class,
        'pdf'   => 'act-gotovn-podmostei.pdf',
        'view'  => 'acts.templates.prilozeniye_gotovn_podmostei',
        'number_field' => 'number_act',
        'validation' => [
            'number_act'       => 'required|string',
            'day'              => 'required|integer',
            'month'            => 'required|string',
            'year'             => 'required|integer',
            'stroika_address'  => 'required|string',
            'lift_type'        => 'required|string',
            'lift_number'      => 'required|string',
            'prim_1'           => 'nullable|string',
            'prim_2'           => 'nullable|string',
            // Подписи
            'sdat_fio'             => 'required|string',
            'sdat_dolzh'           => 'required|string',
            'sdat_sign'            => 'nullable|string',
            'sdat_decipher'        => 'nullable|string',
            'sdat_date'            => 'nullable|string',
            'prinyal_an_fio'       => 'nullable|string',
            'prinyal_an_dolzh'     => 'nullable|string',
            'prinyal_an_sign'      => 'nullable|string',
            'prinyal_an_decipher'  => 'nullable|string',
            'prinyal_an_date'      => 'nullable|string',
            'prinyal_mont_fio'     => 'nullable|string',
            'prinyal_mont_dolzh'   => 'nullable|string',
            'prinyal_mont_sign'    => 'nullable|string',
            'prinyal_mont_decipher'=> 'nullable|string',
            'prinyal_mont_date'    => 'nullable|string',
            'passport_id'          => 'required|exists:passports,id',
        ],
        'fields' => [
            'number_act',
            'day',
            'month',
            'year',
            'stroika_address',
            'lift_type',
            'lift_number',
            'prim_1',
            'prim_2',
            'sdat_fio',
            'sdat_dolzh',
            'sdat_sign',
            'sdat_decipher',
            'sdat_date',
            'prinyal_an_fio',
            'prinyal_an_dolzh',
            'prinyal_an_sign',
            'prinyal_an_decipher',
            'prinyal_an_date',
            'prinyal_mont_fio',
            'prinyal_mont_dolzh',
            'prinyal_mont_sign',
            'prinyal_mont_decipher',
            'prinyal_mont_date',
        ],
    ],
    'prilozeniye_gotovn_lift' => [
        'group' => 'Лифтовое оборудование',
        'label' => 'Акт готовности лифта к производству отделочных работ',
        'model' => \App\Models\PrilozeniyeGotovnLift::class,
        'pdf' => 'gotovn_lift.pdf',
        'view'  => 'acts.templates.prilozeniye_gotovn_lift',
        'number_field' => 'number_acts',
        'validation' => [
            'number_acts'     => 'required|string',
            'day'             => 'required|integer',
            'month'           => 'required|string',
            'year'            => 'required|integer',
            'stroika_address' => 'required|string',
            'lift'            => 'required|string',
            'number_lift'     => 'required|string',
            'tnp'             => 'required|string',
            'tnp_dolzj'       => 'nullable|string',
            'an'              => 'nullable|string',
            'an_dolzh'         => 'nullable|string',
            'mo'              => 'nullable|string',
            'mo_dolzh'         => 'nullable|string',
            'otdel_raboty'    => 'nullable|string',
            'lift_number'     => 'nullable|string',
            'passport_id'     => 'required|exists:passports,id',
        ],
        'fields' => [
            'number_acts',
            'day',
            'month',
            'year',
            'stroika_address',
            'lift',
            'number_lift',
            'tnp',
            'tnp_dolzj',
            'an',
            'an_dplj',
            'mo',
            'mo_dolj',
            'otdel_raboty',
            'lift_number',
        ],
    ],

];
