<?php
namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class PassportActType extends Model
{
    protected $fillable = [
        'passport_id',
        'act_key',
        'is_selected',
        'hidden_works',
        'intermediate_accepts',
        'prilozeniye_1',
        'prilozeniye_2',
        'prilozeniye_3',
        'prilozeniye_4',
        'prilozeniye_5',
        'prilozeniye_6',
        'prilozeniye_7',
        'prilozeniye_8',
        'prilozeniye_9',
        'prilozeniye_10',
        'prilozeniye_11',
        'prilozeniye_12',
        'prilozeniye_13',
        'prilozeniye_14',
        'prilozeniye_15',
        'prilozeniye_16',
        'prilozeniye_17',
        'prilozeniye_18',
        'prilozeniye_19',
        'prilozeniye_20',
        'prilozeniye_21',
        'prilozeniye_22',
        'prilozeniye_23',
        'prilozeniye_24',
        'prilozeniye_25',
        'prilozeniye_26',
        'prilozeniye_27',
        'prilozeniye_28',
        'prilozeniye_29',
        'prilozeniye_30',
        'prilozeniye_31',
        'prilozeniye_32',
        'prilozeniye_33',
        'prilozeniye_34',
        'prilozeniye_35',
        'prilozeniye_36',
        'prilozeniye_37',
        'prilozeniye_38',
        'prilozeniye_39',
        'prilozeniye_40',
        'prilozeniye_41',
        'prilozeniye_42',
        'prilozeniye_43',
        'prilozeniye_44',
        'prilozeniye_45',
        'prilozeniye_46',
        'prilozeniye_47',
        'prilozeniye_48',
        'prilozeniye_49',
        'prilozeniye_50',
        'prilozeniye_51',
        'prilozeniye_52',
        'prilozeniye_53',
        'prilozeniye_54',
        'prilozeniye_55',
        'prilozeniye_56',
        'prilozeniye_57',
        'prilozeniye_58',
        'prilozeniye_59',
        'prilozeniye_60',
        'prilozeniye_61',
        'prilozeniye_62',
        'prilozeniye_63',
        'prilozeniye_64',
        'prilozeniye_65',
        'prilozeniye_66',
        'prilozeniye_67',
        'prilozeniye_68',
        'prilozeniye_69',
        'prilozeniye_70',
        'prilozeniye_71',
        'prilozeniye_72',
        'prilozeniye_73',
        'prilozeniye_74',
        'prilozeniye_75',
        'prilozeniye_gotovn_podmosteis',
        'prilozeniye_gotovn_lifts',
    ];


    public function passport()
    {
        return $this->belongsTo(Passport::class);
    }
}
